// <auto-generated />
using System;
using DemoWebApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoWebApp.DAL.Migrations
{
    [DbContext(typeof(NorthwindDbContext))]
    partial class NorthwindDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoWebApp.DAL.Models.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("CategoryId");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("CategoryName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<byte[]>("Picture")
                    .HasColumnType("varbinary(max)");

                b.Property<string>("PictureUrl")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Categories");
            });

            modelBuilder.Entity("DemoWebApp.DAL.Models.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasColumnName("ProductId");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<int?>("CategoryId")
                    .HasColumnType("int");

                b.Property<bool>("Discontinued")
                    .HasColumnType("bit");

                b.Property<int>("PageNumber")
                    .HasColumnType("int");

                b.Property<int>("PageSize")
                    .HasColumnType("int");

                b.Property<string>("ProductName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("QuantityPerUnit")
                    .HasColumnType("nvarchar(max)");

                b.Property<short?>("ReorderLevel")
                    .HasColumnType("smallint");

                b.Property<int?>("SupplierId")
                    .HasColumnType("int");

                b.Property<decimal?>("UnitPrice")
                    .HasColumnType("decimal(18,2)");

                b.Property<short?>("UnitsInStock")
                    .HasColumnType("smallint");

                b.Property<short?>("UnitsOnOrder")
                    .HasColumnType("smallint");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.ToTable("Products");
            });

            modelBuilder.Entity("DemoWebApp.DAL.Models.Product", b =>
            {
                b.HasOne("DemoWebApp.DAL.Models.Category", "Category")
                    .WithMany("Products")
                    .HasForeignKey("CategoryId");

                b.Navigation("Category");
            });

            modelBuilder.Entity("DemoWebApp.DAL.Models.Category", b =>
            {
                b.Navigation("Products");
            });
#pragma warning restore 612, 618
        }
    }
}
